odp/ui/admin/views/archives.py
from flask import Blueprint, render_template, request

from odp.const import ODPScope
from odp.ui.base import api

bp = Blueprint('archives', __name__)


@bp.route('/')
@api.view(ODPScope.ARCHIVE_READ)
def index():
    page = request.args.get('page', 1)
    archives = api.get(f'/archive/?page={page}')
    return render_template('archive_index.html', archives=archives)


@bp.route('/<id>')
@api.view(ODPScope.ARCHIVE_READ)
def detail(id):
    archive = api.get(f'/archive/{id}')
    return render_template('archive_detail.html', archive=archive)

odp/ui/admin/views/keywords.py
from flask import Blueprint, render_template, request

from odp.const import ODPScope
from odp.ui.base import api
from odp.ui.base.templates import create_btn, delete_btn, edit_btn

bp = Blueprint('keywords', __name__)


@bp.route('/')
@api.view(ODPScope.KEYWORD_READ_ALL)
def index():
    vocabulary_ids = request.args.getlist('vocabulary')
    page = request.args.get('page', 1)

    api_filter = ''
    ui_filter = ''
    for vocabulary_id in vocabulary_ids:
        api_filter += f'&vocabulary_id={vocabulary_id}'
        ui_filter += f'&vocabulary={vocabulary_id}'

    keywords = api.get(f'/keyword/?page={page}{api_filter}')

    return render_template(
        'keyword_index.html',
        keywords=keywords,
        filter_=ui_filter,
        buttons=[
            create_btn(scope=ODPScope.KEYWORD_ADMIN),
        ]
    )


@bp.route('/<id>')
@api.view(ODPScope.KEYWORD_READ_ALL)
def detail(id):
    keyword = api.get(f'/keyword/{id}')
    return render_template(
        'keyword_detail.html',
        keyword=keyword,
        buttons=[
            edit_btn(object_id=id, scope=ODPScope.KEYWORD_ADMIN),
            delete_btn(object_id=id, scope=ODPScope.KEYWORD_ADMIN, prompt_args=(id,)),
        ]
    )

odp/ui/admin/views/packages.py
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for

from odp.const import ODPPackageTag, ODPScope
from odp.lib.client import ODPAPIError
from odp.ui.admin.forms import PackageForm
from odp.ui.base import api
from odp.ui.base.forms import ResourceSearchForm
from odp.ui.base.lib import tags, utils
from odp.ui.base.templates import create_btn, delete_btn, edit_btn

bp = Blueprint('packages', __name__)


@bp.route('/')
@api.view(ODPScope.PACKAGE_READ_ALL)
def index():
    page = request.args.get('page', 1)
    provider_id = request.args.get('provider')
    ui_filter = f'&provider={provider_id}' if provider_id else ''

    packages = api.get(
        '/package/all/',
        provider_id=provider_id,
        page=page,
    )

    return render_template(
        'package_index.html',
        packages=packages,
        filter_=ui_filter,
        buttons=[
            create_btn(scope=ODPScope.PACKAGE_ADMIN),
        ]
    )


@bp.route('/<id>')
@api.view(ODPScope.PACKAGE_READ_ALL)
def detail(id):
    package = api.get(f'/package/all/{id}')
    resources = utils.pagify(package['resources'])

    doi_tag = tags.get_tag_instance(package, ODPPackageTag.DOI)
    contrib_tags = tags.get_tag_instances(package, ODPPackageTag.CONTRIBUTOR)

    return render_template(
        'package_detail.html',
        package=package,
        resources=resources,
        doi_tag=doi_tag,
        contrib_tags=contrib_tags,
        buttons=[
            edit_btn(object_id=id, scope=ODPScope.PACKAGE_ADMIN),
            delete_btn(object_id=id, scope=ODPScope.PACKAGE_ADMIN, prompt_args=(id,)),
        ]
    )


@bp.route('/new', methods=('GET', 'POST'))
@api.view(ODPScope.PACKAGE_ADMIN)
def create():
    form = PackageForm(request.form)
    utils.populate_provider_choices(form.provider_id, include_none=True)

    resource_search_form = ResourceSearchForm()
    utils.populate_provider_choices(resource_search_form.resource_provider_id, include_none=True)

    if request.method == 'POST' and form.validate():
        try:
            package = api.post('/package/admin/', dict(
                provider_id=form.provider_id.data,
                title=form.title.data,
                resource_ids=form.resource_ids.data,
            ))
            flash(f"Package <b>{package['title']}</b> has been created.", category='success')
            return redirect(url_for('.detail', id=package['id']))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template(
        'package_edit.html',
        form=form,
        resource_search_form=resource_search_form,
    )


@bp.route('/<id>/edit', methods=('GET', 'POST'))
@api.view(ODPScope.PACKAGE_ADMIN)
def edit(id):
    package = api.get(f'/package/all/{id}')

    # separate get/post form instantiation to resolve
    # ambiguity of missing vs empty multiselect field
    if request.method == 'POST':
        form = PackageForm(request.form)
    else:
        form = PackageForm(data=package)

    utils.populate_provider_choices(form.provider_id)

    # formatting of checkbox labels must match that of addResources() in the template
    form.resource_ids.choices = [
        (res['id'], f"{res['title']} [{res['filename']} | {res['size']} | {res['mimetype']}]")
        for res in package['resources']
    ]

    resource_search_form = ResourceSearchForm()
    utils.populate_provider_choices(resource_search_form.resource_provider_id)

    if request.method == 'POST' and form.validate():
        try:
            api.put(f'/package/admin/{id}', dict(
                provider_id=form.provider_id.data,
                title=(title := form.title.data),
                resource_ids=form.resource_ids.data,
            ))
            flash(f'Package <b>{title}</b> has been updated.', category='success')
            return redirect(url_for('.detail', id=id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template(
        'package_edit.html',
        package=package,
        form=form,
        resource_search_form=resource_search_form,
    )


@bp.route('/<id>/delete', methods=('POST',))
@api.view(ODPScope.PACKAGE_ADMIN)
def delete(id):
    api.delete(f'/package/admin/{id}')
    flash(f'Package {id} has been deleted.', category='success')
    return redirect(url_for('.index'))


@bp.route('/fetch-resources/<provider_id>')
# no @api.view because this is called via ajax
def fetch_resources(provider_id):
    """Endpoint for populating resource selection popup."""
    include_packaged = request.args.get('include_packaged')
    try:
        return api.get(
            '/resource/all/',
            provider_id=provider_id,
            exclude_packaged=not include_packaged,
            size=0,
        )
    except ODPAPIError as e:
        abort(e.status_code, e.error_detail)

odp/ui/admin/views/records.py
import json

from flask import Blueprint, flash, g, redirect, render_template, request, url_for

from odp.const import ODPCollectionTag, ODPRecordTag, ODPScope
from odp.lib.client import ODPAPIError
from odp.ui.admin.forms import RecordFilterForm, RecordForm, RecordTagEmbargoForm, RecordTagNoteForm, RecordTagQCForm
from odp.ui.base import api
from odp.ui.base.lib import tags, utils
from odp.ui.base.templates import Button, ButtonTheme, create_btn, delete_btn, edit_btn

bp = Blueprint('records', __name__)


@bp.route('/')
@api.view(ODPScope.RECORD_READ)
def index():
    page = request.args.get('page', 1)
    id_q = request.args.get('id_q')
    title_q = request.args.get('title_q')
    collection_ids = request.args.getlist('collection')
    parent_id = request.args.get('parent')

    api_filter = ''
    ui_filter = ''
    if id_q:
        api_filter += f'&identifier_q={id_q}'
        ui_filter += f'&id_q={id_q}'
    if title_q:
        api_filter += f'&title_q={title_q}'
        ui_filter += f'&title_q={title_q}'
    for collection_id in collection_ids:
        api_filter += f'&collection_id={collection_id}'
        ui_filter += f'&collection={collection_id}'
    if parent_id:
        api_filter += f'&parent_id={parent_id}'
        ui_filter += f'&parent={parent_id}'

    filter_form = RecordFilterForm(request.args)
    # utils.populate_collection_choices(filter_form.collection)  # unused

    records = api.get(f'/record/?page={page}{api_filter}')
    catalogs = api.get('/catalog/')

    return render_template(
        'record_index.html',
        records=records,
        filter_=ui_filter,
        filter_form=filter_form,
        buttons=[
            create_btn(scope=ODPScope.RECORD_WRITE),
        ],
        catalog_urls={
            catalog['id']: catalog['url'] for catalog in catalogs['items']
        },
    )


@bp.route('/<id>')
@api.view(ODPScope.RECORD_READ)
def detail(id):
    record = api.get(f'/record/{id}')
    catalog_records = api.get(f'/record/{id}/catalog')
    audit_records = api.get(f'/record/{id}/audit')
    catalogs = api.get('/catalog/')

    nosearch_btn = Button(
        label='No search',
        endpoint='.tag_notsearchable',
        theme=ButtonTheme.warning,
        prompt='Are you sure you want to tag the record as not searchable?',
        object_id=id,
        scope=ODPScope.RECORD_NOSEARCH,
    )
    if notsearchable_tag := tags.get_tag_instance(record, ODPRecordTag.NOTSEARCHABLE):
        nosearch_btn.label = 'Searchable'
        nosearch_btn.endpoint = '.untag_notsearchable'
        nosearch_btn.theme = ButtonTheme.success
        nosearch_btn.prompt = 'Are you sure you want the record to be searchable?'

    retract_btn = Button(
        label='Retract',
        endpoint='.tag_retracted',
        theme=ButtonTheme.danger,
        prompt='Are you sure you want to retract the record from public catalogs?',
        object_id=id,
        scope=ODPScope.RECORD_RETRACT,
    )
    if retracted_tag := tags.get_tag_instance(record, ODPRecordTag.RETRACTED):
        retract_btn.label = 'Un-retract'
        retract_btn.endpoint = '.untag_retracted'
        retract_btn.theme = ButtonTheme.success
        retract_btn.prompt = 'Are you sure you want to cancel the record retraction?'

    return render_template(
        'record_detail.html',
        record=record,
        migrated_tag=tags.get_tag_instance(record, ODPRecordTag.MIGRATED),
        notsearchable_tag=notsearchable_tag,
        collection_notsearchable_tag=tags.get_tag_instance(record, ODPCollectionTag.NOTSEARCHABLE),
        retracted_tag=retracted_tag,
        qc_tags=tags.get_tag_instances(record, ODPRecordTag.QC),
        qc_tag_enabled=ODPScope.RECORD_QC in g.user_permissions,
        embargo_tags=tags.get_tag_instances(record, ODPRecordTag.EMBARGO),
        embargo_tag_enabled=ODPScope.RECORD_EMBARGO in g.user_permissions,
        note_tags=tags.get_tag_instances(record, ODPRecordTag.NOTE),
        note_tag_enabled=ODPScope.RECORD_NOTE in g.user_permissions,
        catalog_records=catalog_records,
        audit_records=audit_records,
        buttons=[
            edit_btn(object_id=id, scope=ODPScope.RECORD_WRITE),
            nosearch_btn,
            retract_btn,
            delete_btn(object_id=id, scope=ODPScope.RECORD_WRITE, prompt_args=(record['doi'] or record['sid'],)),
        ],
        create_btn=create_btn(scope=ODPScope.RECORD_WRITE),
        filter_form=RecordFilterForm(),
        catalog_urls={
            catalog['id']: catalog['url'] for catalog in catalogs['items']
        },
    )


@bp.route('/new', methods=('GET', 'POST'))
@api.view(ODPScope.RECORD_WRITE)
def create():
    form = RecordForm(request.form)
    utils.populate_collection_choices(form.collection_id, include_none=True)
    utils.populate_metadata_schema_choices(form.schema_id)

    if request.method == 'POST' and form.validate():
        api_route = '/record/'
        if ODPScope.RECORD_ADMIN in g.user_permissions:
            api_route += 'admin/'

        try:
            record = api.post(api_route, dict(
                doi=(doi := form.doi.data) or None,
                sid=(sid := form.sid.data) or None,
                collection_id=form.collection_id.data,
                schema_id=form.schema_id.data,
                metadata=json.loads(form.metadata.data),
            ))
            flash(f'Record {doi or sid} has been created.', category='success')
            return redirect(url_for('.detail', id=record['id']))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template('record_edit.html', form=form)


@bp.route('/<id>/edit', methods=('GET', 'POST'))
@api.view(ODPScope.RECORD_WRITE)
def edit(id):
    record = api.get(f'/record/{id}')

    form = RecordForm(request.form, data=record)
    utils.populate_collection_choices(form.collection_id)
    utils.populate_metadata_schema_choices(form.schema_id)

    if request.method == 'POST' and form.validate():
        api_route = '/record/'
        if ODPScope.RECORD_ADMIN in g.user_permissions:
            api_route += 'admin/'

        try:
            api.put(api_route + id, dict(
                doi=(doi := form.doi.data) or None,
                sid=(sid := form.sid.data) or None,
                collection_id=form.collection_id.data,
                schema_id=form.schema_id.data,
                metadata=json.loads(form.metadata.data),
            ))
            flash(f'Record {doi or sid} has been updated.', category='success')
            return redirect(url_for('.detail', id=id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template('record_edit.html', record=record, form=form)


@bp.route('/<id>/delete', methods=('POST',))
@api.view(ODPScope.RECORD_WRITE)
def delete(id):
    api_route = '/record/'
    if ODPScope.RECORD_ADMIN in g.user_permissions:
        api_route += 'admin/'

    api.delete(api_route + id)
    flash(f'Record {id} has been deleted.', category='success')
    return redirect(url_for('.index'))


@bp.route('/<id>/tag/qc', methods=('GET', 'POST'))
@api.view(ODPScope.RECORD_QC)
def tag_qc(id):
    record = api.get(f'/record/{id}')

    # separate get/post form instantiation to resolve
    # ambiguity of missing vs false boolean field
    if request.method == 'POST':
        form = RecordTagQCForm(request.form)
    else:
        record_tag = tags.get_tag_instance(record, ODPRecordTag.QC, user=True)
        form = RecordTagQCForm(data=record_tag['data'] if record_tag else None)

    if request.method == 'POST' and form.validate():
        try:
            api.post(f'/record/{id}/tag', dict(
                tag_id=ODPRecordTag.QC,
                data={
                    'pass_': form.pass_.data,
                    'comment': form.comment.data,
                },
            ))
            flash(f'{ODPRecordTag.QC} tag has been set.', category='success')
            return redirect(url_for('.detail', id=id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template(
        'record_tag_edit.html',
        record=record, form=form, tag_endpoint='.tag_qc',
    )


@bp.route('/<id>/untag/qc/<tag_instance_id>', methods=('POST',))
@api.view(ODPScope.RECORD_QC)
def untag_qc(id, tag_instance_id):
    api_route = '/record/'
    if ODPScope.RECORD_ADMIN in g.user_permissions:
        api_route += 'admin/'

    api.delete(f'{api_route}{id}/tag/{tag_instance_id}')
    flash(f'{ODPRecordTag.QC} tag has been removed.', category='success')
    return redirect(url_for('.detail', id=id))


@bp.route('/<id>/tag/note', methods=('GET', 'POST'))
@api.view(ODPScope.RECORD_NOTE)
def tag_note(id):
    record = api.get(f'/record/{id}')

    if request.method == 'POST':
        form = RecordTagNoteForm(request.form)
    else:
        record_tag = tags.get_tag_instance(record, ODPRecordTag.NOTE, user=True)
        form = RecordTagNoteForm(data=record_tag['data'] if record_tag else None)

    if request.method == 'POST' and form.validate():
        try:
            api.post(f'/record/{id}/tag', dict(
                tag_id=ODPRecordTag.NOTE,
                data={
                    'comment': form.comment.data,
                },
            ))
            flash(f'{ODPRecordTag.NOTE} tag has been set.', category='success')
            return redirect(url_for('.detail', id=id))

        except ODPAPIError as e:
            if response := api.handle_error(e):
                return response

    return render_template(
        'record_tag_edit.html',
        record=record, form=form, tag_endpoint='.tag_note',
    )


@bp.route('/<id>/untag/note/<tag_instance_id>', methods=('POST',))
@api.view(ODPScope.RECORD_NOTE)
def untag_note(id, tag_instance_id):
    api_route = '/record/'
    if ODPScope.RECORD_ADMIN in g.user_permissions:

odp/ui/admin/views/resources.py
from flask import Blueprint, render_template, request

from odp.const import ODPScope
from odp.ui.base import api

bp = Blueprint('resources', __name__)


@bp.route('/')
@api.view(ODPScope.RESOURCE_READ_ALL)
def index():
    page = request.args.get('page', 1)
    archive_id = request.args.get('archive')
    package_id = request.args.get('package')
    provider_id = request.args.get('provider')

    ui_filter = ''
    if archive_id:
        ui_filter += f'&archive={archive_id}'
    if package_id:
        ui_filter += f'&package={package_id}'
    if provider_id:
        ui_filter += f'&provider={provider_id}'

    resources = api.get(
        '/resource/all/',
        page=page,
        archive_id=archive_id,
        package_id=package_id,
        provider_id=provider_id,
    )

    return render_template(
        'resource_index.html',
        resources=resources,
        filter_=ui_filter,
    )


@bp.route('/<id>')
@api.view(ODPScope.RESOURCE_READ_ALL)
def detail(id):
    resource = api.get(f'/resource/all/{id}')

    return render_template(
        'resource_detail.html',
        resource=resource,
    )

odp/ui/admin/templates/collection_view.html
{% extends 'base.html' %}
{% from 'content.j2' import render_info, render_buttons,
    render_table, render_tag_table, render_audit_table, obj_link %}

{% block web_title %}
    {{ super() }} |
    {% block heading %}
        Collection: {{ collection.name }}
    {% endblock %}
{% endblock %}

{% block content %}
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#info" type="button" role="tab">
                Info
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#projects" type="button" role="tab">
                Projects
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#infrastructures" type="button" role="tab">
                Infrastructures
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#audit-log" type="button" role="tab">
                Audit Log
            </button>
        </li>
    </ul>
    <div class="tab-content">
        <div id="info" class="tab-pane fade show active" role="tabpanel">
            {% call(prop) render_info(collection, 'Key', 'Name', 'Provider', 'DOI key', 'Records',
                    'Published', 'Frozen', 'Harvested', 'Searchable', 'Projects', 'Infrastructures', 'Timestamp') %}
                {% if prop == 'Key' %}
                    {{ collection.key }}
                {% elif prop == 'Name' %}
                    {{ collection.name }}
                {% elif prop == 'Provider' %}
                    {{ obj_link('providers', collection.provider_id, collection.provider_key) }}
                {% elif prop == 'DOI key' %}
                    {{ collection.doi_key if collection.doi_key }}
                {% elif prop == 'Records' %}
                    <a href="{{ url_for('records.index', collection=collection.id) }}" class="text-decoration-none">
                        {{ collection.record_count }}
                    </a>
                {% elif prop == 'Published' %}
                    {% if published_tag %}
                        {{ published_tag.timestamp|timestamp }}
                        {% if published_tag.user_id %}
                            by {{ obj_link('users', published_tag.user_id, published_tag.user_name) }}
                        {% endif %}
                    {% endif %}
                {% elif prop == 'Frozen' %}
                    {% if frozen_tag %}
                        {{ frozen_tag.timestamp|timestamp }} by {{ obj_link('users', frozen_tag.user_id, frozen_tag.user_name) }}
                    {% endif %}
                {% elif prop == 'Harvested' %}
                    {{ 'True (ignore record QC when publishing)' if harvested_tag else 'False' }}
                {% elif prop == 'Searchable' %}
                    {% if notsearchable_tag %}
                        False: tagged as not searchable at {{ notsearchable_tag.timestamp|timestamp }} by {{ obj_link('users', notsearchable_tag.user_id, notsearchable_tag.user_name) }}
                    {% else %}
                        True
                    {% endif %}
                {% elif prop == 'Projects' %}
                    {{ project_tags['items']|map(attribute='data.project')|sort|join(', ') }}
                {% elif prop == 'Infrastructures' %}
                    {{ infrastructure_tags['items']|map(attribute='data.infrastructure')|sort|join(', ') }}
                {% elif prop == 'Timestamp' %}
                    {{ collection.timestamp|timestamp }}
                {% endif %}
            {% endcall %}

            {{ render_buttons(buttons) }}
        </div>
        <div id="projects" class="tab-pane fade" role="tabpanel">
            {{ render_tag_table(collection, project_tags, '.tag_project', '.untag_project', project_tag_enabled,
               project='Project', comment='Comment') }}
        </div>
        <div id="infrastructures" class="tab-pane fade" role="tabpanel">
            {{ render_tag_table(collection, infrastructure_tags, '.tag_infrastructure', '.untag_infrastructure', infrastructure_tag_enabled,
               infrastructure='Infrastructure', comment='Comment') }}
        </div>
        <div id="audit-log" class="tab-pane fade" role="tabpanel">
            {% call(audit_record) render_audit_table(audit_records) %}
                {% if audit_record.table == 'collection' %}
                    <a href="{{ url_for('.view_audit_detail', id=collection.id, collection_audit_id=audit_record.audit_id) }}" class="text-decoration-none">
                        Collection
                    </a>
                {% elif audit_record.table == 'collection_tag' %}
                    <a href="{{ url_for('.view_tag_audit_detail', id=collection.id, collection_tag_audit_id=audit_record.audit_id) }}" class="text-decoration-none">
                        {{ audit_record.tag_id }}
                    </a>
                {% endif %}
            {% endcall %}
        </div>
    </div>
{% endblock %}

odp/ui/admin/templates/package_detail.html
{% extends 'admin_base.html' %}
{% from 'content.j2' import render_info, render_buttons, render_table, obj_link, obj_links %}

{% block web_title %}
    {{ super() }} |
    {% block heading %}
        Package: {{ package.title }}
    {% endblock %}
{% endblock %}

{% block content %}
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#info" type="button" role="tab">
                Info
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#resources" type="button" role="tab">
                Resources
            </button>
        </li>
    </ul>

    <div class="tab-content">
        <div id="info" class="tab-pane fade show active" role="tabpanel">
            {% call(prop) render_info(package,
                    'Title', 'DOI', 'Contributors', 'Provider', 'Resources', 'Status', 'Record', 'Timestamp') %}

                {% if prop == 'Title' %}
                    {{ package.title }}

                {% elif prop == 'DOI' %}
                    {{ doi_tag.data.doi if doi_tag }}

                {% elif prop == 'Contributors' %}
                    {% for contrib_tag in contrib_tags['items'] %}
                        <p>{{ contrib_tag.data.role }}: {{ contrib_tag.data.name }}</p>
                    {% endfor %}

                {% elif prop == 'Provider' %}
                    {{ obj_link('providers', package.provider_id, package.provider_key) }}

                {% elif prop == 'Resources' %}
                    <a href="{{ url_for('resources.index', package=package.id) }}" class="text-decoration-none">
                        {{ package.resource_ids | length }}
                    </a>

                {% elif prop == 'Status' %}
                    {{ package.status }}

                {% elif prop == 'Record' %}
                    {{ package.record_doi or package.record_sid }}

                {% elif prop == 'Timestamp' %}
                    {{ package.timestamp | timestamp }}

                {% endif %}
            {% endcall %}

            {{ render_buttons(buttons) }}
        </div>

        <div id="resources" class="tab-pane fade" role="tabpanel">
            {% call(resource) render_table(resources,
                    'Title', 'File name', 'File size', 'Provider', 'Archive',
                    archive=archive, hide_id=true
            ) %}
                <th scope="row">{{ obj_link('resources', resource.id, resource.title) }}</th>
                <td>{{ resource.filename }}</td>
                <td>{{ resource.size | bytes }}</td>
                <td>{{ obj_link('providers', resource.provider_id, resource.provider_key) }}</td>
                <td>{{ obj_links('archives', resource.archive_paths.keys()) }}</td>
            {% endcall %}
        </div>
    </div>
{% endblock %}

odp/ui/admin/templates/provider_detail.html
{% extends 'admin_base.html' %}
{% from 'content.j2' import render_info, render_buttons, obj_links, render_audit_table %}

{% block web_title %}
    {{ super() }} |
    {% block heading %}
        Provider: {{ provider.name }}
    {% endblock %}
{% endblock %}

{% block content %}
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#info" type="button" role="tab">
                Info
            </button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" data-bs-toggle="tab" data-bs-target="#audit-log" type="button" role="tab">
                Audit Log
            </button>
        </li>
    </ul>
    <div class="tab-content">
        <div id="info" class="tab-pane fade show active" role="tabpanel">
            {% call(prop) render_info(provider,
                    'Key', 'Name', 'Collections', 'Packages', 'Users', 'Clients', 'Timestamp'
            ) %}
                {% if prop == 'Key' %}
                    {{ provider.key }}
                {% elif prop == 'Name' %}
                    {{ provider.name }}
                {% elif prop == 'Collections' %}
                    {{ obj_links('collections', provider.collection_keys, newlines=True) }}
                {% elif prop == 'Packages' %}
                    <a href="{{ url_for('packages.index', provider=provider.id) }}" class="text-decoration-none">
                        {{ provider.package_count }}
                    </a>
                {% elif prop == 'Users' %}
                    {{ obj_links('users', provider.user_names, newlines=True) }}
                {% elif prop == 'Clients' %}
                    {{ obj_links('clients', provider.client_ids, newlines=True) }}
                {% elif prop == 'Timestamp' %}
                    {{ provider.timestamp | timestamp }}
                {% endif %}
            {% endcall %}

            {{ render_buttons(buttons) }}
        </div>

        <div id="audit-log" class="tab-pane fade" role="tabpanel">
            {% call(audit_record) render_audit_table(audit_records) %}
                <a href="{{ url_for('.audit_detail', id=provider.id, audit_id=audit_record.audit_id) }}" class="text-decoration-none">
                    Provider
                </a>
            {% endcall %}
        </div>
    </div>
{% endblock %}

odp/ui/admin/templates/vocabulary_index.html
{% extends 'admin_base.html' %}
{% from 'content.j2' import render_table %}

{% block web_title %}
    {{ super() }} |
    {% block heading %}
        Vocabularies
    {% endblock %}
{% endblock %}

{% block content %}
    {% call(vocabulary) render_table(vocabularies, 'URI', 'Keywords', 'Editable') %}
        <td>
            {{ vocabulary.uri }}
        </td>
        <td>
            <a href="{{ url_for('keywords.index', vocabulary=vocabulary.id) }}" class="text-decoration-none">
                {{ vocabulary.keyword_count }}
            </a>
        </td>
        <td>
            {{ not vocabulary.static }}
        </td>
    {% endcall %}
{% endblock %}